spring:
  application:
    name: TeamSoft

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/TeamSoft-DB
    username: postgres
    password: pascual0815*
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

security:
  jwt:
    key:
      private: d1015495a3db2e85eb17d547b37249d1addeec83e509e1b072f0c18e51cae0f2
    user:
      generator: teamsoft-api
    expiration-ms: 7200000

server:
  port: 8081

