spring:
  application:
    name: TeamSoft
  config:
    import: "classpath:config.properties"

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true

security:
  jwt:
    key:
      private: ${jwt.key.private}
    user:
      generator: ${jwt.user.generator}
    expiration-ms: ${jwt.expiration-ms}

server:
  port: ${server.port}

ext-modules:
  combination-mod:
    default-key: ${ext-modules.combination-mod.default-key}
    base-url: ${ext-modules.combination-mod.base-url}

    services:
      combine-team:
        endpoint: ${ext-modules.combination-mod.services.combine.endpoint}
#       Custom endpoint api-key can be defined
#       api-key: ${ext-modules.combination-mod.services.combine.api-key}



